sonar.projectKey=fluency-Platform
sonar.projectName=Fluency Platform
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=backEnd/eureka/src/main/java,backEnd/Gateway/src/main/java,backEnd/microservices/User/src/main/java,backEnd/microservices/Quiz/src/main/java,frontEnd/EnglishPlateforme/src/app
sonar.tests=backEnd/eureka/src/test/java,backEnd/Gateway/src/test/java,backEnd/microservices/User/src/test/java,backEnd/microservices/Quiz/src/test/java,frontEnd/EnglishPlateforme/src/app

sonar.java.binaries=backEnd/eureka/target/classes,backEnd/Gateway/target/classes,backEnd/microservices/User/target/classes,backEnd/microservices/Quiz/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/uploads/**,**/run-logs/**,**/*.log,**/.env,**/.idea/**,**/.vscode/**,**/Dockerfile,**/.dockerignore,**/docker-compose*.yml,AGENT.md,AI_HANDOFF_SUMMARY.md,CHANGE_LOG.md,DEVOPS_HISTORY.md,DEVOPS_REPORT.md,PROJECT_AUDIT.md,PROJECT_MASTER_REPORT.md,SPRINT2_SIMPLE_TRACKER.md
sonar.test.inclusions=**/*Test.java,**/*.spec.ts
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/target/**
