global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'forum-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['forum-service:8082']

  - job_name: 'resource-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8078']
