global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "eureka"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka:8761"]

  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8090"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8081"]

  - job_name: "quiz-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["quiz-service:8056"]
