spring.application.name=courses
server.port=8081

spring.cloud.config.enabled=true
# Allow local startup when config-server isn't running on localhost:8899.
spring.config.import=optional:configserver:http://localhost:8899